version: '3.7'
services:
  app:
    volumes:
      - .:/app
    container_name: notal-autograder
    build: .
    labels:
      - com.host.description=autograder
    restart: on-failure
    ports:
      - "5000:5000"